# git - Version control system
if command -v git >/dev/null 2>&1; then
  alias gs='git status'
  alias gc='git commit'
  alias gca='git commit -a'
  alias gcm='git commit -m'
  alias gcam='git commit -am'
  alias ga='git add'
  alias gaa='git add --all'
  alias gb='git branch'
  alias gco='git checkout'
  alias gcb='git checkout -b'
  alias gd='git diff'
  alias gdc='git diff --cached'
  alias gl='git log --oneline --graph --decorate'
  alias gll='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit'
  alias gp='git push'
  alias gpl='git pull'
  alias gf='git fetch'
  alias gm='git merge'
  alias grh='git reset --hard'
  alias grs='git reset --soft'
  alias gst='git stash'
  alias gstp='git stash pop'
fi
